//
// Created by sebas on 1/15/20.
//

#ifndef WPP_LIST_DIR_HPP
#define WPP_LIST_DIR_HPP

#include "response.hpp"
#include "request.hpp"

#include <unordered_map>

namespace WPP {
    const std::unordered_map<std::string_view, std::string_view> mime = {
            {"atom", "application/atom+xml"},
            {"hqx", "application/atom+xml"},
            {"cpt", "application/mac-compactpro"},
            {"mathml", "application/mathml+xml"},
            {"doc", "application/msword"},
            {"bin", "application/octet-stream"},
            {"dms", "application/octet-stream"},
            {"lha", "application/octet-stream"},
            {"lzh", "application/octet-stream"},
            {"exe", "application/octet-stream"},
            {"class", "application/octet-stream"},
            {"so", "application/octet-stream"},
            {"dll", "application/octet-stream"},
            {"dmg", "application/octet-stream"},
            {"oda", "application/oda"},
            {"ogg", "application/ogg"},
            {"pdf", "application/pdf"},
            {"ai", "application/postscript"},
            {"eps", "application/postscript"},
            {"ps", "application/poststscript"},
            {"rdf", "application/rdf+xml"},
            {"smi", "application/smil"},
            {"smil", "application/smil"},
            {"gram", "application/srgs"},
            {"grxml", "application/srgs+xml"},
            {"air", "application/vnd.adobe.apollo-application-installer-package+zip"},
            {"mif", "application/vnd.mif"},
            {"xul", "application/vnd.mozilla.xul+xml"},
            {"xls", "application/vnd.ms-excel"},
            {"ppt", "application/vnd.ms-powerpoint"},
            {"rm", "application/vnd.rn-realmedia"},
            {"wbxml", "application/vnd.wap.wbxml"},
            {"wmlc", "application/vnd.wap.wmlc"},
            {"wmlsc", "application/vnd.wap.wmlscriptc"},
            {"vxml", "application/voicexml+xml"},
            {"bcpio", "application/x-bcpio"},
            {"vcd", "application/x-cdlink"},
            {"pgn", "application/x-chess-pgn"},
            {"cpio", "application/x-cpio"},
            {"csh", "application/x-csh"},
            {"dcr", "application/x-director"},
            {"dir", "application/x-director"},
            {"dxr", "application/x-director"},
            {"dvi", "application/x-dvi"},
            {"spl", "application/x-futuresplash"},
            {"gtar", "application/x-gtar"},
            {"hdf", "application/x-hdf"},
            {"js", "application/x-javascript"},
            {"latex", "application/x-latex"},
            {"sh", "application/x-sh"},
            {"shar", "application/x-shar"},
            {"swf", "application/x-shockwave-flash"},
            {"sit", "application/x-stuffit"},
            {"sv4cpio", "application/x-sv4cpio"},
            {"sv4crc", "application/x-sv4crc"},
            {"tar", "application/x-tar"},
            {"tcl", "application/x-tcl"},
            {"tex", "application/x-tex"},
            {"man", "application/x-troff-man"},
            {"me", "application/x-troff-me"},
            {"ms", "application/x-troff-ms"},
            {"xml", "application/xml"},
            {"xsl", "application/xml"},
            {"xhtml", "application/xhtml+xml"},
            {"xht", "application/xhtml+xml"},
            {"dtd", "application/xml-dtd"},
            {"xslt", "application/xslt+xml"},
            {"zip", "application/zip"},
            {"mp3", "audio/mpeg"},
            {"mpga", "audio/mpeg"},
            {"mp2", "audio/mpeg"},
            {"m3u", "audio/x-mpegurl"},
            {"wav", "audio/x-wav"},
            {"pdb", "chemical/x-pdb"},
            {"xyz", "chemical/x-xyz"},
            {"bmp", "image/bmp"},
            {"cgm", "image/cgm"},
            {"gif", "image/gif"},
            {"ief", "image/ief"},
            {"jpg", "image/jpeg"},
            {"jpeg", "image/jpeg"},
            {"jpe", "image/jpeg"},
            {"png", "image/png"},
            {"svg", "image/svg+xml"},
            {"wbmp", "image/vnd.wap.wbmp"},
            {"ras", "image/x-cmu-raster"},
            {"ico", "image/x-icon"},
            {"pnm", "image/x-portable-anymap"},
            {"pbm", "image/x-portable-bitmap"},
            {"pgm", "image/x-portable-graymap"},
            {"ppm", "image/x-portable-pixmap"},
            {"rgb", "image/x-rgb"},
            {"xbm", "image/x-xbitmap"},
            {"xpm", "image/x-xpixmap"},
            {"xwd", "image/x-xwindowdump"},
            {"css", "text/css"},
            {"html", "text/html"},
            {"htm", "text/html"},
            {"txt", "text/plain"},
            {"asc", "text/plain"},
            {"rtx", "text/richtext"},
            {"rtf", "text/rtf"},
            {"tsv", "text/tab-separated-values"},
            {"wml", "text/vnd.wap.wml"},
            {"wmls", "text/vnd.wap.wmlscript"},
            {"etx", "text/x-setext"},
            {"mpg", "video/mpeg"},
            {"mpeg", "video/mpeg"},
            {"mpe", "video/mpeg"},
            {"flv", "video/x-flv"},
            {"avi", "video/x-msvideo"},
            {"movie", "video/x-sgi-movie"}
    };


    void list_dir(Request &req, Response &res);
};
#endif //WPP_LIST_DIR_HPP
